### PR TITLE
Support cmake & c++11

### PR DESCRIPTION
**Pull request by denleyhsiao**
* Use cmake build.
* Use c++11 variadic templates.
* Use CppUnitLite test.

### CODE REVIEW

**Comment by catnapgames** [comment]
@denleyhsiao thanks. Would you like to take over this repo? I would like to remove it from my GitHub account.

**Comment by denleyhsiao** [comment]
OK,thanks


发送自我的三星 Galaxy 智能手机。
-------- 原始信息 --------由： Tomas Andrle <notifications@github.com> 日期: 18/6/4  07:03  (GMT+08:00) 收件人： catnapgames/SigSlot <SigSlot@noreply.github.com> 抄送： Denley Hsiao <denley@justtodo.com>, Mention <mention@noreply.github.com> 主题： Re: [catnapgames/SigSlot] Support cmake & c++11 (#2) 
@denleyhsiao thanks. Would you like to take over this repo? I would like to remove it from my GitHub account.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/catnapgames/SigSlot/pull/2#issuecomment-394198915","url":"https://github.com/catnapgames/SigSlot/pull/2#issuecomment-394198915","name":"View Pull Request"},"description":"View this Pull Request on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/catnapgames/SigSlot","title":"catnapgames/SigSlot","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/catnapgames/SigSlot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@catnapgames in #2: @denleyhsiao thanks. Would you like to take over this repo? I would like to remove it from my GitHub account."}],"action":{"name":"View Pull Request","url":"https://github.com/catnapgames/SigSlot/pull/2#issuecomment-394198915"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [catnapgames/SigSlot] Support cmake \u0026 c++11 (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Tomas Andrle**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@catnapgames",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"catnapgames/SigSlot\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/catnapgames/SigSlot/pull/2#issuecomment-394198915"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 331890534\n}"
}
],
"themeColor": "26292E"
}

**Comment by catnapgames** [comment]
@denleyhsiao tried to do a repo transfer but since SigSlot already exists in your account, it didn't work. I see why I couldn't just delete mine at this point -- you already have all the changes, agreed?

**Comment by denleyhsiao** [comment]
@catnapgames That's OK

**Comment by catnapgames** [comment]
OK thank you and take care.

**Pull request merged**
